pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    stages {

        stage('Build & Run Tests') {
            steps {
                dir('Introductiontoselenium') {
                    sh 'mvn clean test'
                }
            }
        }
    }

    post {
        always {
            junit 'Introductiontoselenium/target/surefire-reports/*.xml'
        }
    }
}
